# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Materi perkuliahan - Penambangan Data A
#subtitle: Buku Materi Perkuliahan Penambangan Data Kelas A
author: Kasyfu Rafi Susanto 
logo: foto.jpeg

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/kasyfurafi-stack/pendata.git # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

execute:
  execute_notebooks: off

# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

html:
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  home_page_in_navbar: true
  extra_footer: ""
  
sphinx:
  config:
    html_theme: sphinx_book_theme
    html_copy_source: true
    html_sourcelink_suffix: ""
    exclude_patterns:
      - ".ipynb_checkpoints"
      - "*~"
    html_static_path:
      - _static
    html_css_files:
      - custom.css